# Ejemplo de cloudbuild.yaml para un microservicio
steps:
# 1. Construir la imagen de Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/[NOMBRE_DEL_SERVICIO]:g$SHORT_SHA', '.']
  dir: '[RUTA_AL_MICROSERVICIO]' # Útil si es un monorepo

# 2. Subir la imagen a Google Container Registry (GCR) o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/[NOMBRE_DEL_SERVICIO]:g$SHORT_SHA']

# 3. Desplegar en Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  args: [
    'gcloud',
    'run',
    'deploy',
    '[NOMBRE_DEL_SERVICIO]', # El nombre de tu servicio en Cloud Run
    '--image',
    'gcr.io/$PROJECT_ID/[NOMBRE_DEL_SERVICIO]:g$SHORT_SHA',
    '--region',
    '[REGION_GCP]', # e.g., us-central1
    '--platform',
    'managed',
    '--allow-unauthenticated' # O --no-allow-unauthenticated si requieres autenticación
  ]
